version: "3.9"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
